### ISSUE TITLE
Replace Apache commons-io with standard Java calls

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/pipeline-steps-doc-generator#316]
The Java 11 runtime and its libraries provide more easily maintained and more familiar utilities to perform the file operations that are currently performed with Apache commons-io.  Recent changes to Apache commons-io library have needed some changes in other parts of Jenkins.  It would be best if the few references to commons-io in this utility were replaced by calls to standard Java 11 methods.

Changes are needed in at least the following files:

* src/main/java/org/jenkinsci/pipeline_steps_doc_generator/DeclarativeSteps.java
* src/main/java/org/jenkinsci/pipeline_steps_doc_generator/PipelineStepExtractor.java
* src/main/java/org/jenkinsci/pipeline_steps_doc_generator/ProcessAsciiDoc.java
* src/main/java/org/jenkinsci/pipeline_steps_doc_generator/ToAsciiDoc.java
* src/test/java/org/jenkinsci/pipeline_steps_doc_generator/ProcessAsciiDocTest.java

```[tasklist]
### Tasks
- [ ] Replace usages of `FileUtils` with equivalents from Java 11
- [ ] Replace usages of `FilenameUtils` with Java 11 equivalents
- [ ] Replace usages of `IOUtils` with Java 11 equivalents
- [ ] Replace usages of `StringEscapeUtils` with Java 11 equivalents
```

**Comment by MarkEWaite** [comment]
> I am Interested in contributing to this issue. In DeclarativeStep file Can I use FileOutputStream to achieve it? `FileUtils.writeStringToFile( new File(declPath, entry.getKey() + ".adoc"), whole9yards, StandardCharsets.UTF_8);`

I believe the [`Files.writeString` method](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html#writeString(java.nio.file.Path,java.lang.CharSequence,java.nio.charset.Charset,java.nio.file.OpenOption...)) is probably an even better choice than `FileOutputStream` as the replacement for `FileUtils.writeStringToFile`.  It could be done with `FileOutputStream` but the `writeString` method seems like it would be easier to read and more concisely describes what is happening.
